server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.116.100:3306/guli_cart
    username: root
    password: root
  redis:
    host: 172.16.116.100
feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.cart.bean
jwt: # 请自己完成配置到配置中心
  pubKeyPath: D:\project-1125\rsa\rsa.pub
  cookieName: GMALL-TOKEN
  userKey: userKey
